# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepstuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='entry timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='entry timestamp')),
            ],
        ),
        migrations.AddField(
            model_name='stuff',
            name='lastmod',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepstuff.Stuff'),
        ),
        migrations.AddField(
            model_name='diff',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepstuff.Stuff'),
        ),
    ]
