# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepstuff', '0002_auto_20170530_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=0)),
                ('isabs', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='entry timestamp')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.RemoveField(
            model_name='diff',
            name='stuff',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stuff',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Diff',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='entry',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepstuff.Stuff'),
        ),
    ]
