# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepstuff', '0004_auto_20170531_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='stren',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stuff',
            name='strenunit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
